import java.time.LocalDateTime;
/** primary_listing_id is generated by SQL and is not an independently writable field. */
public record ListingPhoto(int id, int listingId, String url, boolean primary,
                           long sortOrder, LocalDateTime createdAt) {}
