-- V1: canonical RentNest schema before Phase 2; structure only, no sample accounts/data.
-- Existing databases must explicitly baseline at version 1 instead of executing this file.
-- Once applied through Flyway, do not edit this file; add a new version instead.

CREATE TABLE `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` CHAR(64) NOT NULL,
  `role` ENUM('RENTER','OWNER','ADMIN') NOT NULL DEFAULT 'RENTER',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('ACTIVE','BANNED') NOT NULL DEFAULT 'ACTIVE',
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `listings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` INT DEFAULT NULL,
  `title` VARCHAR(120) NOT NULL,
  `listing_type` ENUM('ROOM','FLAT','APARTMENT','OFFICE','PARKING') DEFAULT NULL,
  `location` VARCHAR(200) NOT NULL,
  `description` TEXT DEFAULT NULL,
  `price_month` DECIMAL(10,2) NOT NULL,
  `deposit` DECIMAL(10,2) DEFAULT NULL,
  `size_sqft` INT UNSIGNED DEFAULT NULL,
  `bedrooms` TINYINT UNSIGNED DEFAULT NULL,
  `bathrooms` TINYINT UNSIGNED DEFAULT NULL,
  `furnished` TINYINT(1) DEFAULT NULL,
  `bachelor_allowed` TINYINT(1) DEFAULT NULL,
  `family_allowed` TINYINT(1) DEFAULT NULL,
  `approval_status` ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  `is_available` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),

  KEY `idx_listings_owner` (`owner_id`),
  KEY `idx_listings_public` (`approval_status`, `is_available`),
  KEY `idx_listings_type` (`listing_type`),
  KEY `idx_listings_price` (`price_month`),

  CONSTRAINT `fk_listings_owner`
    FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
    ON DELETE SET NULL,

  CONSTRAINT `chk_listings_price`
    CHECK (`price_month` >= 0),

  CONSTRAINT `chk_listings_deposit`
    CHECK (`deposit` IS NULL OR `deposit` >= 0),

  CONSTRAINT `chk_listings_size`
    CHECK (`size_sqft` IS NULL OR `size_sqft` > 0),

  CONSTRAINT `chk_listings_furnished`
    CHECK (`furnished` IS NULL OR `furnished` IN (0,1)),

  CONSTRAINT `chk_listings_bachelor`
    CHECK (`bachelor_allowed` IS NULL OR `bachelor_allowed` IN (0,1)),

  CONSTRAINT `chk_listings_family`
    CHECK (`family_allowed` IS NULL OR `family_allowed` IN (0,1)),

  CONSTRAINT `chk_listings_available`
    CHECK (`is_available` IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `listing_photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `listing_id` INT NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  KEY `idx_listing_photos_listing` (`listing_id`),
  KEY `idx_listing_photos_primary` (`listing_id`, `is_primary`, `sort_order`),

  CONSTRAINT `fk_listing_photos_listing`
    FOREIGN KEY (`listing_id`) REFERENCES `listings` (`id`)
    ON DELETE CASCADE,

  CONSTRAINT `chk_listing_photos_primary`
    CHECK (`is_primary` IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `amenities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_amenities_code` (`code`),
  UNIQUE KEY `uq_amenities_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `listing_amenities` (
  `listing_id` INT NOT NULL,
  `amenity_id` INT NOT NULL,

  PRIMARY KEY (`listing_id`, `amenity_id`),
  KEY `idx_listing_amenities_amenity` (`amenity_id`),

  CONSTRAINT `fk_listing_amenities_listing`
    FOREIGN KEY (`listing_id`) REFERENCES `listings` (`id`)
    ON DELETE CASCADE,

  CONSTRAINT `fk_listing_amenities_amenity`
    FOREIGN KEY (`amenity_id`) REFERENCES `amenities` (`id`)
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `listing_id` INT NOT NULL,
  `renter_id` INT NOT NULL,
  `owner_id` INT DEFAULT NULL,
  `start_date` DATE DEFAULT NULL,
  `end_date` DATE DEFAULT NULL,
  `total_amount` DECIMAL(10,2) DEFAULT 0.00,
  `status` ENUM('PENDING','PENDING_OWNER_APPROVAL','CONFIRMED','CANCELLED','APPROVED','REJECTED') DEFAULT 'PENDING',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  KEY `idx_bookings_listing` (`listing_id`),
  KEY `idx_bookings_renter` (`renter_id`),
  KEY `idx_bookings_owner` (`owner_id`),

  CONSTRAINT `fk_bookings_listing`
    FOREIGN KEY (`listing_id`) REFERENCES `listings` (`id`)
    ON DELETE CASCADE,

  CONSTRAINT `fk_bookings_renter`
    FOREIGN KEY (`renter_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE,

  CONSTRAINT `fk_bookings_owner`
    FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `listing_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_favorites_user_listing` (`user_id`, `listing_id`),
  KEY `idx_favorites_listing` (`listing_id`),

  CONSTRAINT `fk_favorites_user`
    FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE,

  CONSTRAINT `fk_favorites_listing`
    FOREIGN KEY (`listing_id`) REFERENCES `listings` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `inquiries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `listing_id` INT NOT NULL,
  `renter_id` INT NOT NULL,
  `message` TEXT DEFAULT NULL,
  `contact` VARCHAR(150) DEFAULT NULL,
  `status` ENUM('Pending','Replied','Closed') DEFAULT 'Pending',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  KEY `idx_inquiries_listing` (`listing_id`),
  KEY `idx_inquiries_renter` (`renter_id`),

  CONSTRAINT `fk_inquiries_listing`
    FOREIGN KEY (`listing_id`) REFERENCES `listings` (`id`)
    ON DELETE CASCADE,

  CONSTRAINT `fk_inquiries_renter`
    FOREIGN KEY (`renter_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `listing_id` INT DEFAULT NULL,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  `message_text` TEXT NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  KEY `idx_messages_receiver` (`receiver_id`),
  KEY `idx_messages_sender_receiver` (`sender_id`, `receiver_id`),
  KEY `idx_messages_listing` (`listing_id`),

  CONSTRAINT `fk_messages_listing`
    FOREIGN KEY (`listing_id`) REFERENCES `listings` (`id`)
    ON DELETE SET NULL,

  CONSTRAINT `fk_messages_sender`
    FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE,

  CONSTRAINT `fk_messages_receiver`
    FOREIGN KEY (`receiver_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NOT NULL,
  `amount` DOUBLE NOT NULL,
  `payment_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  KEY `idx_payments_booking` (`booking_id`),

  CONSTRAINT `fk_payments_booking`
    FOREIGN KEY (`booking_id`) REFERENCES `bookings` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

CREATE TABLE `admin_actions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin_id` INT NOT NULL,
  `action_type` VARCHAR(100) NOT NULL,
  `target_id` INT NOT NULL,
  `details` TEXT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  KEY `idx_admin_actions_admin` (`admin_id`),

  CONSTRAINT `fk_admin_actions_admin`
    FOREIGN KEY (`admin_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
